name: Lint and Format

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: |
          echo "Running ESLint..."
          if ! npm run lint; then
            echo "::error::ESLint found issues. Run 'npm run lint:fix' to automatically fix some issues."
            exit 1
          fi

      - name: Run Prettier check
        run: |
          echo "Running Prettier format check..."
          if ! npm run format:check; then
            echo "::error::Prettier found formatting issues. Run 'npm run format' to fix formatting."
            exit 1
          fi

      - name: Success message
        if: success()
        run: echo "✅ All linting and formatting checks passed!"